# This names the project
name: farm-fresh-v2-0-project

services:
  # Define the service for the application
  app:
    # Build the image if it doesn't exist
    build:
      context: . # Use the current directory as the build context
      dockerfile: dockerfile # Specify the Dockerfile to use for building the image

    # Specify the image to use for the container
    image: farm-fresh-image
    # Specify the container name
    container_name: farm-fresh-app-container
    ports:
      - "8000:8000" # Map port 8000 on the host to port 8000 in the container
    volumes:
      - .:/farm-fresh-app # Mount the current directory to /farm-fresh-app (taken from WORKDIR in the dockerfile) in the container

  # Define the service for the database
  db:
    # Use the official PostgreSQL image from Docker Hub
    image: postgres:17
    # Specify the container name
    container_name: farm-fresh-postgres-db
    # Specify the restart policy for the container
    restart: always # Restart the container if it stops
    # Set environment variables for the database
    environment:
      POSTGRES_USER: farm_fresh_user # Database user
      POSTGRES_PASSWORD: farm_fresh_password # Database password
      POSTGRES_DB: farm_fresh_db # Database name
    # Define the volume for the database data
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data in a named volume
    # Specify ports to expose
    ports:
      - "5432:5432" # Map port 5432 on the host to port 5432 in the container

volumes:
  postgres_data: # Define a named volume for the database data
