name: farm-fresh-v2-0-project

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: farm-fresh-development-image
    container_name: farm-fresh-development-app-container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/farm-fresh-app

  db:
    image: postgres:17
    container_name: farm-fresh-development-postgres-db
    restart: always
    environment:
      POSTGRES_USER: farm_fresh_user
      POSTGRES_PASSWORD: farm_fresh_password
      POSTGRES_DB: farm_fresh_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
