# This names the project
name: farm-fresh-v2-0-project

services:
  # Define the service for the application
  app:
    # Build the image if it doesn't exist
    build:
      context: . # Use the current directory as the build context
      dockerfile: dockerfile # Specify the Dockerfile to use for building the image

    # Specify the image to use for the container
    image: farm-fresh-production-image
    # Specify the container name
    container_name: farm-fresh-production-app-container
    ports:
      - "8000:8000" # Map port 8000 on the host to port 8000 in the container
    volumes:
      - .:/farm-fresh-production-app # Mount the current directory to /farm-fresh-app (taken from WORKDIR in the dockerfile) in the container
