name: farm-fresh-v2-0-project

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/farm-fresh-app

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: farm_fresh_user
      POSTGRES_PASSWORD: farm_fresh_password
      POSTGRES_DB: farm_fresh_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  stripe-cli:
    image: stripe/stripe-cli:latest
    profiles:
      - stripe
    depends_on:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - stripe_cli_config:/root/.config/stripe
    command: >
      listen
      --events payment_intent.succeeded,payment_intent.payment_failed
      --forward-to http://host.docker.internal:8000/checkout/wh/
    stdin_open: true
    tty: true

volumes:
  postgres_data:
  stripe_cli_config:
