# Generated by Django 5.2.1 on 2025-05-22 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('packaging_type', models.CharField(choices=[('Piece', 'Piece'), ('Bag', 'Bag'), ('Box', 'Box'), ('Bottle', 'Bottle'), ('Jar', 'Jar'), ('Plastic Wrap', 'Plastic Wrap'), ('Foil Wrap', 'Foil Wrap')], max_length=50)),
                ('weight', models.CharField(choices=[('1 Kg', '1 Kg'), ('500g', '500g'), ('250g', '250g'), ('200g', '200g'), ('120g', '120g'), ('100g', '100g'), ('1 ltr', '1 Ltr'), ('390ml', '390ml'), ('500ml', '500ml'), ('ca. 250-350g', 'ca. 250-350g'), ('ca. 0.9-1.1kg', 'ca. 0.9 - 1.1kg'), ('10 pieces of 53g+', '10 pieces of 53g+')], max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Packaging',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('organic', models.BooleanField(default=False)),
                ('in_season', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('packaging', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.packaging')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.producer')),
            ],
        ),
    ]
